# Change these first
owner: schollz # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: getcroc.schollz.com
    url: https://getcroc.schollz.com/
  - name: findabooktoread.com
    url: https://findabooktoread.com/
  - name: pianos.pub
    url: https://pianos.pub/
  - name: schollz.com
    url: https://schollz.com/
  - name: teoperator.com
    url: https://teoperator.com/
  - name: www.poetrygenerator.ninja
    url: https://www.poetrygenerator.ninja/
  - name: norns.online
    url: https://norns.online/
  - name: averagedrecipe
    url: https://averagedrecipe.com/
  - name: cowyo
    url: https://cowyo.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
